apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/* # config files location
build:
  local:
    push: false # Don't push to DockerHub
  artifacts:
    - image: youssefegla/auth
      context: "../services/auth" # directory where it contains files for the image
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts" # location of files
            dest: . # sync files to corresponding path inside the container
